### ISSUE TITLE
week 3 2018 changes checklist

### ISSUE THREAD

**Issue by ebretl** [RoboJackets/software-training#136]
- [x] Call STL by full acronym
- [x] STSL -> RJRobot
- [x] remove ISO standard from the slide 2 quote
- [x] add overview of STL structure (containers and algos that operate on those containers)
- [x] ~int~s doesn't render right
- [x] render functions with ()
- [x] end points to after the last element
- [x] operator* should go with ++ and --
- [x] begin and end return iterators, not elements (picture to show where the iterators point)
- [x] is the copy slide useful?
- [x] igvc robots bigoli -> jessi
- [x] nth_element in slides
- [x] write-up for challenge (median line sample)
- [x] remove robot time! slide
